time_units: generations
generation_time: 1
demes:
- name: Anc
  epochs:
  - {end_time: 140000, start_size: 10000}
- name: Anc_Pan
  ancestors: [Anc]
  epochs:
  - {end_time: 79600, start_size: 10000}
- name: Anc_Chimp
  ancestors: [Anc_Pan]
  epochs:
  - {end_time: 28000, start_size: 10000}
- name: Bonobo
  ancestors: [Anc_Pan]
  epochs:
  - {end_time: 0, start_size: 10000}
- name: Western
  ancestors: [Anc_Chimp]
  epochs:
  - {end_time: 0, start_size: 10000}
migrations:
- demes: [Bonobo, Anc_Chimp]
  rate: 1e-07
  start_time: 60000.0
  end_time: 48000.0
